### ISSUE TITLE
Import to Prestashop 1.7

### ISSUE THREAD

**Issue by mikelpz** [yusttas/jk_opengraph#1]
HI!

I try to import the module to Prestashop 1.7 and it throws an error: invalid zip. I just download the sources from github as a zip file and import it.

How should I install it? 

Thanks!

**Comment by yusttas** [comment]
Hello,   

I renamed repository as jk_opengraph instead of just opengraph, because zip/folder name should be same as main module file. But github also adds "-master" to zip/folder name.   

So what you should do is download zip again, extract it, and rename folder from jk_opengraph-master to just jk_opengraph. Make sure files are in this folder and not in subfolder. Zip it again and try install it.

**Comment by mikelpz** [comment]
Thanks!
